[versions]
kotlin = "2.3.0"
junit = "4.13.2"
jspecify = "1.0.0"

android-min = "24"
android-compile = "36.1"
android-agp = "8.12.3"

androidx-coreKtx = "1.17.0"
androidx-appcompat = "1.7.1"
androidx-junit = "1.3.0"
androidx-espressoCore = "3.7.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espressoCore" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android-agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
