[versions]
kotlin = "2.3.0"
agp = "8.12.0"

android-min = "24"
android-target = "36.1"

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
android-library-multiplatform = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
